monolog:
    handlers:
        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error
            formatter: 'monolog.formatter.json'

        
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            # max number of log files to keep
            # defaults to zero, which means infinite files
            max_files: 10
            formatter: 'monolog.formatter.json'